# Generated by Django 4.1.3 on 2022-11-21 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(max_length=100, verbose_name='Tag Type')),
                ('tag_value', models.CharField(max_length=100, verbose_name='Tag Value')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'unique_together': {('tag_type', 'tag_value')},
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='Row')),
                ('column', models.IntegerField(verbose_name='Column')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('INVALID', 'Invalid')], max_length=50, verbose_name='Status')),
                ('tag', models.ForeignKey(limit_choices_to={'deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='SeedMgmt.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Seed',
                'verbose_name_plural': ' Seeds',
            },
        ),
    ]
