# Generated by Django 4.1.3 on 2022-11-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeedMgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seed',
            options={'verbose_name': 'Seed', 'verbose_name_plural': 'Seeds'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': ' Tags'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='seed',
            unique_together={('row', 'column')},
        ),
    ]
